// Renders links.mjs into index.html. Zero dependencies; run `node build.mjs`.
//
// Why a generator rather than hand-written HTML or a client-side render:
//   - the handoff asks for the links to be a data list, and 12 near-identical cards
//     of hand-written markup drift (a stale class, a missing arrow, nobody notices);
//   - rendering client-side would ship JS to do what static HTML does better on a
//     page whose entire purpose is outbound links — worse for crawlers, worse on a
//     cold phone connection, and broken with JS off.
// So the data is a list, and the artifact is plain HTML. index.html is committed.
import { writeFileSync, mkdirSync, copyFileSync, rmSync } from "node:fs";
import { GROUPS, SOCIALS, ICONS, TAGLINE, SPIN_DURATION } from "./links.mjs";

// Escape anything that reaches an HTML text node or attribute. The copy contains
// "&" and "×" today, and a future link title is exactly where an unescaped
// apostrophe or ampersand would silently break the page.
const esc = (s) =>
  String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])
  );

const card = (l) => {
  const icon = ICONS[l.icon];
  if (!icon) throw new Error(`Unknown icon "${l.icon}" on link "${l.title}"`);
  // External links get rel=noopener. target=_blank is deliberately NOT set: this is
  // a navigation hub, and hijacking the user's tab decision is rude.
  const ext = /^https?:\/\//i.test(l.href);
  return `        <a class="card${l.featured ? " is-featured" : ""}" href="${esc(l.href)}"${ext ? ' rel="noopener"' : ""}>
          <span class="card-icon" aria-hidden="true">${icon}</span>
          <span class="card-text">
            <span class="card-title">${esc(l.title)}</span>
            <span class="card-desc">${esc(l.desc)}</span>
          </span>
          <span class="card-arrow" aria-hidden="true">&rarr;</span>
        </a>`;
};

const group = (g) => `      <section class="group" aria-labelledby="grp-${esc(g.title.toLowerCase().replace(/[^a-z]+/g, "-"))}">
        <h2 class="group-title" id="grp-${esc(g.title.toLowerCase().replace(/[^a-z]+/g, "-"))}">${esc(g.title)}</h2>
${g.links.map(card).join("\n")}
      </section>`;

const social = (s) =>
  `      <a class="social" href="${esc(s.href)}"${/^https?:/i.test(s.href) ? ' rel="noopener"' : ""}>${s.svg}${esc(s.label)}</a>`;

const html = `<!doctype html>
<!-- GENERATED by build.mjs from links.mjs — do not edit by hand.
     To change a link, edit links.mjs and re-run \`node build.mjs\`. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>BU Spark! — Hub</title>
<meta name="description" content="${esc(TAGLINE)}">
<link rel="icon" href="assets/spark-logo.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Montserrat:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
<style>:root { --spin-duration: ${SPIN_DURATION}; }</style>
</head>
<body>
  <div class="page">
    <header class="hero">
      <div class="hero-glow" aria-hidden="true"></div>
      <div class="holo-float">
        <div class="holo-flicker">
          <img class="holo-img" src="assets/spark-logo.png" alt="" width="150" height="150">
        </div>
      </div>
      <div class="holo-floor" aria-hidden="true"></div>
      <h1 class="wordmark">BU SPARK<span class="bang">!</span></h1>
      <p class="tagline">${esc(TAGLINE)}</p>
    </header>

    <nav class="groups" aria-label="Spark! links">
${GROUPS.map(group).join("\n")}
    </nav>

    <nav class="socials" aria-label="Social links">
${SOCIALS.map(social).join("\n")}
    </nav>
    <p class="byline">bu.edu/spark &middot; Boston University</p>
  </div>
</body>
</html>
`;

writeFileSync(new URL("./index.html", import.meta.url), html);

// Also stage dist/ — exactly what a visitor needs and nothing else. wrangler.jsonc
// serves this directory rather than the repo root, so links.mjs, build.mjs, the
// README and package.json never reach the edge.
//
// index.html is written to BOTH places on purpose: the root copy is committed and
// CI checks it is current (it is the reviewable artifact), while dist/ is gitignored
// and exists only to be uploaded.
const dist = new URL("./dist/", import.meta.url);
rmSync(dist, { recursive: true, force: true });
mkdirSync(new URL("./assets/", dist), { recursive: true });
writeFileSync(new URL("./index.html", dist), html);
for (const [from, to] of [
  ["./styles.css", "./styles.css"],
  ["./assets/spark-logo.png", "./assets/spark-logo.png"],
]) {
  copyFileSync(new URL(from, import.meta.url), new URL(to, dist));
}

const n = GROUPS.flatMap((g) => g.links).length;
console.log(`index.html + dist/ written — ${GROUPS.length} groups, ${n} links, ${SOCIALS.length} socials`);
const placeholders = GROUPS.flatMap((g) => g.links).filter((l) => l.href === "#").map((l) => l.title);
if (placeholders.length) console.log(`  ${placeholders.length} still pointing at "#": ${placeholders.join(", ")}`);
